=== HorridoJoho/YANModPack/data/scripts/YANModPack/YANBuffer/data/xml/xsd/buffer_npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="buffer_npcs">
    	<complexType>
    		<sequence maxOccurs="1" minOccurs="1">
    			<element name="buffer_npc" maxOccurs="unbounded" minOccurs="0">
    				<complexType>
    					<sequence maxOccurs="1" minOccurs="1">
    						<element name="buff_cat" maxOccurs="unbounded" minOccurs="0">
    							<complexType>
    								<attribute name="ident" type="NCName" use="required"/>
    								<attribute name="is_preset" type="boolean" use="required"/>
    							</complexType>
    						</element>
    					</sequence>
    					<attribute name="id" type="positiveInteger" use="required"/>
    					<attribute name="can_heal" type="boolean" use="required"/>
    					<attribute name="can_cancel" type="boolean" use="required"/>
    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== HorridoJoho/YANModPack/data/scripts/YANModPack/YANBuffer/data/xml/buffer_npcs.xml
<?xml version="1.0" encoding="utf-8"?>
<buffer_npcs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/buffer_npcs.xsd">
	<buffer_npc id="1000006" can_heal="true" can_cancel="true">
		<buff_cat ident="BC_FIGHTER" is_preset="true"/>
		<buff_cat ident="BC_MAGE" is_preset="true"/>

		<buff_cat ident="BC_BUFFS" is_preset="false"/>
		<buff_cat ident="BC_SONGS" is_preset="false"/>
		<buff_cat ident="BC_DANCES" is_preset="false"/>
		<buff_cat ident="BC_CHANTS" is_preset="false"/>
		<buff_cat ident="BC_DWARVEN" is_preset="false"/>
		<buff_cat ident="BC_RESIST" is_preset="false"/>
		<buff_cat ident="BC_SPECIAL" is_preset="false"/>
		<buff_cat ident="BC_OVERLORD" is_preset="false"/>
	</buffer_npc>
</buffer_npcs>
